import Head from 'next/head'
import { Inter, Libre_Baskerville } from 'next/font/google'
import NavBar from '@/components/NavBar'
import { BsArrowRight } from "react-icons/bs"
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Programmes from '@/components/Programmes'
import Current from '@/components/Current'
import News from '@/components/News'
import Links from '@/components/Links'

const inter = Libre_Baskerville({ weight: '700', subsets: ['latin'] })
const inter3 = Libre_Baskerville({ weight: '400', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>University of Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Hero />
        <Programmes />
        <Current />
        <News />
        <Links />
        <Footer />
      </main>
    </>
  )
}
