import Head from 'next/head'
import { Inter, Libre_Baskerville } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Programmes from '@/components/Programmes'
import Current from '@/components/Current'
import News from '@/components/News'
import Links from '@/components/Links'
import MobHeader from '@/components/MobHeader'
import MobFooter from '@/components/MobFooter'


export default function Home() {
  return (
    <>
      <Head>
        <title>University of Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <MobHeader/>
        <Hero />
        <Programmes />
        <Current />
        <News />
        <Links />
        <div className='md:hidden'>
          <div className='fixed gap-2 py-2 px-4 flex items-center -rotate-90 -right-[3.2rem] top-[50%] bg-[#e6e6e6] z-50 text-xl'>
          <img src="./svgs/message.svg" alt="" />
            <p className='text-black'>feedbacks</p>
          </div>
        </div>
       
      </main>
    </>
  )
}
